name: Lint

on: push

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [flake8, black, mypy]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run linter
        run: tox -e ${{ matrix.linter }}
